<?php

namespace App\Docs;

use OpenApi\Attributes as OA;

#[OA\Info(title: 'MasterPOS API', version: '1.0.0')]
#[OA\SecurityScheme(securityScheme: 'bearerAuth', type: 'http', scheme: 'bearer', bearerFormat: 'Token')]
class OpenApi
{
    #[OA\Post(path: '/api/auth/register', tags: ['Auth'], summary: 'Tenant registration', responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/auth/login', tags: ['Auth'], summary: 'Login', responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/auth/logout', tags: ['Auth'], summary: 'Logout', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/auth/me', tags: ['Auth'], summary: 'Profile', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function auth(): void {}

    #[OA\Get(path: '/api/products', tags: ['Products'], summary: 'List products', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/products', tags: ['Products'], summary: 'Create product', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/products/{id}', tags: ['Products'], summary: 'Get product', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Put(path: '/api/products/{id}', tags: ['Products'], summary: 'Update product', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Delete(path: '/api/products/{id}', tags: ['Products'], summary: 'Delete product', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/products/low-stock', tags: ['Products'], summary: 'Low stock products', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function products(): void {}

    #[OA\Get(path: '/api/categories', tags: ['Categories'], summary: 'List categories', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/categories', tags: ['Categories'], summary: 'Create category', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Put(path: '/api/categories/{id}', tags: ['Categories'], summary: 'Update category', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Delete(path: '/api/categories/{id}', tags: ['Categories'], summary: 'Delete category', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function categories(): void {}

    #[OA\Post(path: '/api/sales', tags: ['Sales'], summary: 'Create sale', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/sales', tags: ['Sales'], summary: 'List sales', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/sales/{id}', tags: ['Sales'], summary: 'Get sale', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/sales/daily-report', tags: ['Sales'], summary: 'Daily report', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/sales/monthly-report', tags: ['Sales'], summary: 'Monthly report', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function sales(): void {}

    #[OA\Get(path: '/api/customers', tags: ['Customers'], summary: 'List customers', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/customers', tags: ['Customers'], summary: 'Create customer', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Put(path: '/api/customers/{id}', tags: ['Customers'], summary: 'Update customer', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Delete(path: '/api/customers/{id}', tags: ['Customers'], summary: 'Delete customer', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/customers/{id}/purchase-history', tags: ['Customers'], summary: 'Purchase history', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function customers(): void {}

    #[OA\Get(path: '/api/inventory', tags: ['Inventory'], summary: 'Inventory list', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/inventory/adjust', tags: ['Inventory'], summary: 'Adjust stock', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/inventory/history', tags: ['Inventory'], summary: 'Inventory history', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function inventory(): void {}

    #[OA\Get(path: '/api/dashboard/stats', tags: ['Dashboard'], summary: 'Dashboard stats', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Get(path: '/api/users', tags: ['Users'], summary: 'List users', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Post(path: '/api/users', tags: ['Users'], summary: 'Create user', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Put(path: '/api/users/{id}/role', tags: ['Users'], summary: 'Update user role', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    #[OA\Delete(path: '/api/users/{id}', tags: ['Users'], summary: 'Delete user', security: [['bearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Success'), new OA\Response(response: 401, description: 'Unauthenticated'), new OA\Response(response: 403, description: 'Forbidden'), new OA\Response(response: 422, description: 'Validation error'), new OA\Response(response: 404, description: 'Not found')])]
    public function dashboardUsers(): void {}
}



